version: '3.8'
services:
  postgres_db:
    image: postgres:latest
    container_name: PostgresCont
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres123
    ports:
      - '5432:5432'
  test-task-service:
    build:
      context: ./
      dockerfile: target/docker-sources/Dockerfile
    image: mgerman.local/mgerman-test-task-service:latest
    environment:
      - "SPRING_PROFILES_ACTIVE=local"
    container_name: mgerman-test-task-service
    depends_on: [ postgres_db ]
    links:
      - postgres_db
    ports:
      - '8080:8080'